import{S as n,i as l}from"./assets/vendor-BrddEoy-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const a of e.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function i(t){if(t.ep)return;t.ep=!0;const e=s(t);fetch(t.href,e)}})();const u="https://pixabay.com/api/",g="46194524-ed8204bc29acf0aaf22e3d7ea";function m(o){const r=new URLSearchParams({q:o.q,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15});return fetch(`${u}?key=${g}&${r}`).then(s=>{if(!s.ok)throw new Error("Something went wrong with the request");return s.json()})}function d(o){const r=document.querySelector(".gallery"),s=o.reduce((t,e)=>t+`
        <li class="gallery-el">
            <a href="${e.largeImageURL}" class="gallery-item">
                <article class="gallery-card">
                    <img class="gallery-img" src="${e.webformatURL}" alt="${e.tags}" />
                    <ul class="list-statistics">
                        <li><h2 class="title-statistics">Likes</h2><p class="data-statistics">${e.likes}</p></li>
                        <li><h2 class="title-statistics">Views</h2><p class="data-statistics">${e.views}</p></li>
                        <li><h2 class="title-statistics">Comments</h2><p class="data-statistics">${e.comments}</p></li>
                        <li><h2 class="title-statistics">Downloads</h2><p class="data-statistics">${e.downloads}</p></li>
                    </ul>
                </article>
            </a>
        </li>`,"");r.innerHTML=s,new n(".gallery a").refresh()}const h=document.querySelector("form"),c=document.querySelector(".loader"),p=document.querySelector(".gallery");h.addEventListener("submit",o=>{o.preventDefault();const r=o.target.elements.q.value.trim();if(!r){l.error({message:"Please enter a search query.",title:"",backgroundColor:"rgba(239, 64, 64, 1)",icon:"my-custom-icon",iconColor:"rgba(255, 255, 255, 1)",messageSize:"16px",titleLineHeight:"1.5",position:"topRight",messageColor:"rgba(255, 255, 255, 1)",maxWidth:"432px"});return}p.innerHTML="",c.style.display="block",m({q:r}).then(s=>{c.style.display="none";const{hits:i}=s;if(i.length===0){l.error({title:"",backgroundColor:"rgba(239, 64, 64, 1)",message:"Sorry, there are no images matching <br>your search query. Please try again!",icon:"my-custom-icon",iconColor:"rgba(255, 255, 255, 1)",messageSize:"16px",titleLineHeight:"1.5",position:"topRight",messageColor:"rgba(255, 255, 255, 1)",maxWidth:"432px"});return}d(i)}).catch(s=>{c.style.display="none",l.error({title:"Error",message:s.message})})});
//# sourceMappingURL=index.js.map
